REGLAS_INICIALES: list[tuple] = [
    ("'hola' in input or 'buenas' in input or 'qué tal' in input", "saludar", 8, "Saludar al usuario"),
    ("'adiós' in input or 'adios' in input or 'hasta luego' in input or 'nos vemos' in input", "despedir", 8, "Despedirse del usuario"),
    ("'gracias' in input or 'graciass' in input or 'thank' in input", "agradecer", 7, "Responder a agradecimientos"),
    ("'quién eres' in input or 'quien eres' in input or 'quién sos' in input or 'presentate' in input", "presentarse", 9, "Presentarse"),
    ("'qué sabes' in input or 'que sabes' in input or 'conocimiento' in input", "listar_conocimiento", 6, "Listar hechos conocidos"),
    ("'reglas' in input or 'muestra las reglas' in input", "listar_reglas", 6, "Listar reglas del sistema"),
    ("'ayuda' in input or 'help' in input or 'qué puedes hacer' in input", "mostrar_ayuda", 9, "Mostrar ayuda"),
    ("input.startswith('recuerda que') or input.startswith('aprende que')", "guardar_hecho", 7, "Guardar un hecho nuevo"),
    ("input.startswith('olvida') or input.startswith('borra')", "olvidar", 6, "Olvidar un hecho"),
    ("input.startswith('qué sabes de') or input.startswith('que sabes de')", "consultar_hecho", 7, "Consultar un hecho específico"),
    ("input.startswith('lee ') or input.startswith('abre ') and 'http' not in input", "leer_archivo", 10, "Leer un archivo del sistema"),
    ("input.startswith('escribe ') or input.startswith('guarda en ')", "escribir_archivo", 10, "Escribir contenido en un archivo"),
    ("input.startswith('lista ') or input.startswith('qué hay en ')", "listar_archivos", 10, "Listar contenido de un directorio"),
    ("input.startswith('borra ') or input.startswith('elimina ')", "eliminar_archivo", 10, "Eliminar un archivo"),
    ("input.startswith('ejecuta ')", "ejecutar_comando", 10, "Ejecutar un comando del sistema"),
    ("input.startswith('abre http') or input.startswith('visita http') or input.startswith('web ')", "web_get", 10, "Obtener contenido de una URL"),
    ("input.startswith('herramientas') or 'qué herramientas' in input", "herramientas_disponibles", 10, "Listar herramientas disponibles"),
    ("input.startswith('crea una herramienta') or input.startswith('genera una herramienta') or input.startswith('haz una herramienta')", "crear_habilidad", 10, "Generar una nueva habilidad"),
    ("input.startswith('aprueba ') or input.startswith('habilita ')", "aprobar_habilidad", 10, "Aprobar una habilidad pendiente"),
    ("input.startswith('habilidades') or input.startswith('lista habilidades') or 'qué habilidades' in input", "listar_habilidades", 7, "Listar habilidades instaladas"),
]
